/* ================================================================
   VITOLA PEDIA — Pipe Tobacco Database
   ================================================================ */

const PIPE_TOBACCOS = [
  {
    id: "lane-1q",
    name: "1-Q",
    brand: "Lane Limited",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Virginia", "Burley", "Black Cavendish"],
    origin: "United States",
    strength: 1,
    roomNote: 5,
    tinWeight: 50,
    price: 11.95,
    rating: 89,
    flavors: ["Vanilla", "Honey", "Caramel", "Sweet", "Cream"],
    description: "America's best-selling pipe tobacco for decades. Lane 1-Q is the definitive mild aromatic — a pillowy blend of Virginias, Burley, and Black Cavendish lightly cased with vanilla and honey. Burns cool and dry with a sweet room note that made it legendary among beginners and seasoned smokers alike. If you've ever smelled a pleasant pipe wafting down the street, there's a good chance it was 1-Q.",
    pairings: ["Coffee", "Apple Cider", "Hot Chocolate"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/p/lane-1-q-pipe-tobacco/1439894/", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/lane-limited-bulk-1-q", price: null },
    ]
  },
  {
    id: "dunhill-early-morning-pipe",
    name: "Early Morning Pipe",
    brand: "Dunhill",
    blendType: "English",
    cut: "Ribbon",
    components: ["Virginia", "Latakia", "Oriental"],
    origin: "United Kingdom",
    strength: 1,
    roomNote: 3,
    tinWeight: 50,
    price: 17.95,
    rating: 90,
    flavors: ["Cedar", "Hay", "Floral", "Mild Latakia", "Sweet"],
    description: "One of Alfred Dunhill's most beloved creations, designed for the first pipe of the day. A light English mixture with a gentle touch of Latakia over a base of bright Virginias and sweet Orientals. Cool, gentle, and refined — it builds complexity as it burns down. Now blended by Peterson under license, the formula remains faithful to the original Dunhill recipe.",
    pairings: ["Black Tea", "Coffee", "Orange Juice"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/peterson-early-morning-pipe-tobacco/DHD-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/peterson-dunhill-early-morning-pipe-50g", price: 16.70 },
    ]
  },
  {
    id: "dunhill-london-mixture",
    name: "London Mixture",
    brand: "Dunhill",
    blendType: "English",
    cut: "Ribbon",
    components: ["Virginia", "Latakia", "Oriental", "Perique"],
    origin: "United Kingdom",
    strength: 2,
    roomNote: 3,
    tinWeight: 50,
    price: 17.95,
    rating: 92,
    flavors: ["Latakia", "Earth", "Cedar", "Spice", "Leather"],
    description: "The classic medium English mixture that defined the London style. London Mixture balances smoky Latakia with sweet Virginias and spicy Orientals, with a hint of Perique adding depth and complexity. A sophisticated smoke that rewards patience — from a gentle, grassy opening to a rich leather-and-earth finish. The true benchmark of the English genre.",
    pairings: ["Scotch Whisky", "Black Coffee", "Aged Bourbon"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/p/dunhill-london-mixture-pipe-tobacco/1439874/", price: null },
    ]
  },
  {
    id: "samuel-gawith-full-virginia-flake",
    name: "Full Virginia Flake",
    brand: "Samuel Gawith",
    blendType: "Virginia",
    cut: "Flake",
    components: ["Virginia"],
    origin: "United Kingdom",
    strength: 2,
    roomNote: 4,
    tinWeight: 250,
    price: 22.95,
    rating: 93,
    flavors: ["Hay", "Bread", "Citrus", "Natural Sweet", "Grass"],
    description: "A pressed flake made entirely from fine Virginia tobaccos, produced at the historic Gawith & Hoggarth factory in Kendal, England. Full Virginia Flake must be rubbed out or folded before packing — a ritual that rewards the patient smoker with natural sweetness, bright hay, a hint of citrus, and a clean, dry finish that develops beautifully from top to bottom. Pure Virginia at its most expressive.",
    pairings: ["Tea", "Lemonade", "Light White Wine"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/samuel-gawith-full-virginia-flake/SGK-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/samuel-gawith-full-virginia-flake-250g", price: null },
    ]
  },
  {
    id: "peterson-irish-flake",
    name: "Irish Flake",
    brand: "Peterson",
    blendType: "Virginia/Perique",
    cut: "Flake",
    components: ["Virginia", "Perique"],
    origin: "Ireland",
    strength: 2,
    roomNote: 4,
    tinWeight: 50,
    price: 13.99,
    rating: 92,
    flavors: ["Fruity", "Spicy", "Sweet", "Plum", "Hay"],
    description: "Peterson's Irish Flake is one of the most celebrated Virginia/Perique blends on the market. Pressed flakes of fine bright Virginias interleaved with peppery Perique from St. James Parish, Louisiana — rubbing them out releases a heady, fruity aroma. Spicy and sweet with a long, natural finish that lingers pleasantly. A cornerstone of any serious pipe tobacco collection.",
    pairings: ["Irish Whiskey", "Tea", "Apple Juice"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/peterson-irish-flake/PTE-TP.html", price: 13.99 },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/peterson-irish-flake-50g", price: 14.50 },
    ]
  },
  {
    id: "mac-baren-hh-old-dark-fired",
    name: "HH Old Dark Fired",
    brand: "Mac Baren",
    blendType: "Dark Fired",
    cut: "Ready Rubbed",
    components: ["Kentucky Fire Cured", "Virginia", "Burley"],
    origin: "Denmark",
    strength: 4,
    roomNote: 2,
    tinWeight: 50,
    price: 15.95,
    rating: 91,
    flavors: ["Campfire", "Dark Earth", "Dried Fruit", "Wood Smoke", "Molasses"],
    description: "Mac Baren's tribute to the classic dark-fired Kentucky tradition. HH Old Dark Fired centers on air-cured and fire-cured Kentucky leaf, imparting a rich, woody campfire character that mingles with sweet Virginias and robust Burley. An acquired taste for experienced smokers — intense, complex, and deeply satisfying on a cold night. Not for the faint of heart.",
    pairings: ["Bourbon", "Dark Beer", "Campfire Coffee"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/mac-baren-hh-old-dark-fired/MRG-TB.html", price: null },
    ]
  },
  {
    id: "gl-pease-quiet-nights",
    name: "Quiet Nights",
    brand: "G.L. Pease",
    blendType: "Balkan",
    cut: "Ribbon",
    components: ["Virginia", "Latakia", "Oriental", "Perique"],
    origin: "United States",
    strength: 3,
    roomNote: 2,
    tinWeight: 57,
    price: 17.50,
    rating: 94,
    flavors: ["Latakia", "Earth", "Spice", "Dark Fruit", "Cedar", "Leather"],
    description: "One of G.L. Pease's finest creations, Quiet Nights is a full-flavored Balkan blend that invites contemplation. Smoky Latakia is tempered by complex Orientals and bright Red Virginias, with just enough Perique to add a peppery, fruity dimension. This is a fireplace blend — rich, layered, and deeply satisfying on a cool evening with something substantial in the glass.",
    pairings: ["Scotch Whisky", "Brandy", "Dark Roast Coffee"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/gl-pease-quiet-nights/GLY-TP.html", price: 17.50 },
    ]
  },
  {
    id: "rattray-hal-o-the-wynd",
    name: "Hal O' The Wynd",
    brand: "Rattray's",
    blendType: "Virginia/Perique",
    cut: "Broken Flake",
    components: ["Virginia", "Perique"],
    origin: "Scotland",
    strength: 3,
    roomNote: 4,
    tinWeight: 100,
    price: 21.95,
    rating: 93,
    flavors: ["Fruity", "Spicy", "Dark Fruit", "Hay", "Sweet Pepper"],
    description: "Named after a character from Sir Walter Scott's 'The Fair Maid of Perth,' Hal O' The Wynd is Rattray's masterwork in the Virginia/Perique tradition. Bold, peppery Perique pushes against naturally sweet Red and Light Virginias in broken flake form — earthy, fruity, and complex with a long, warming finish. A quintessential Scottish blend for afternoon reflection.",
    pairings: ["Single Malt Scotch", "Dark Tea", "Port Wine"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/rattray-s-hal-o--the-wynd/RAJ-TP.html", price: 14.94 },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/rattrays-hal-o-the-wynd-100g", price: null },
    ]
  },
  {
    id: "solani-aged-burley-flake-636",
    name: "Aged Burley Flake No. 636",
    brand: "Solani",
    blendType: "Virginia/Burley",
    cut: "Flake",
    components: ["Virginia", "Burley"],
    origin: "Germany",
    strength: 2,
    roomNote: 4,
    tinWeight: 50,
    price: 13.95,
    rating: 93,
    flavors: ["Nuts", "Cream", "Natural Sweet", "Hay", "Bread"],
    description: "A German masterwork of restraint and balance. Solani 636 presses aged Virginia and Burley leaf into a dense, aromatic flake that burns slowly and evenly. No topping, no casing — just pure leaf, aged to bring out natural sweetness and nuttiness. The result is a naturally sweet, creamy, and satisfying smoke that rewards those willing to slow down and pay attention.",
    pairings: ["Coffee", "Beer", "Iced Tea"],
    image: null,
    buyLinks: []
  },
  {
    id: "cornell-diehl-autumn-evening",
    name: "Autumn Evening",
    brand: "Cornell & Diehl",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Virginia", "Burley", "Black Cavendish"],
    origin: "United States",
    strength: 2,
    roomNote: 5,
    tinWeight: 57,
    price: 13.95,
    rating: 91,
    flavors: ["Maple", "Caramel", "Vanilla", "Toasted Nuts", "Sweet"],
    description: "Cornell & Diehl's most beloved aromatic. Autumn Evening takes a robust Burley-Virginia base and tops it lightly with maple and vanilla — resulting in a naturally sweet smoke that tastes as good as it smells. The Black Cavendish adds moisture and a silky, smooth texture. As close to a perfect Sunday afternoon smoke as any tobacco in production.",
    pairings: ["Bourbon", "Apple Cider", "Hot Coffee"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/cornell-and-diehl-autumn-evening/001-CDA.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/copy-of-cornell-diehl-autumn-evening-8oz", price: null },
    ]
  },
  {
    id: "mac-baren-original-choice",
    name: "Original Choice",
    brand: "Mac Baren",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Virginia", "Burley", "Black Cavendish"],
    origin: "Denmark",
    strength: 1,
    roomNote: 5,
    tinWeight: 100,
    price: 17.95,
    rating: 89,
    flavors: ["Sweet", "Vanilla", "Caramel", "Mild Spice", "Honey"],
    description: "Mac Baren's Original Choice is the quintessential Danish aromatic — mild, smooth, and sweetly satisfying. Virginia, Burley, and Black Cavendish are blended in the classic Danish tradition and lightly topped with sweet floral and vanilla notes. A pleasant room note and effortless burn make it an excellent everyday aromatic that punches well above its price point.",
    pairings: ["Coffee", "Milk Tea", "Hot Chocolate"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/mac-baren-classics-original-choice/MBT-TP.html", price: null },
    ]
  },
  {
    id: "capstan-original-flake-blue",
    name: "Original Flake Blue",
    brand: "Capstan",
    blendType: "Virginia",
    cut: "Flake",
    components: ["Virginia"],
    origin: "United Kingdom",
    strength: 2,
    roomNote: 4,
    tinWeight: 50,
    price: 15.95,
    rating: 91,
    flavors: ["Hay", "Natural Sweet", "Citrus", "Toast", "Grass"],
    description: "Capstan is one of Britain's oldest and most enduring pipe tobacco brands, with origins in the Victorian era. The Blue (Medium) flake is pure pressed Virginia leaf — unadulterated tobacconicness at its finest, relying entirely on natural sweetness for its character. Pack it, slow down, and enjoy natural Virginia sweetness, bright grass, and a clean, toasty finish.",
    pairings: ["Black Tea", "Ginger Beer", "White Wine"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/capstan-original-flake/CPB-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/capstan-flake-blue-50g", price: 24.99 },
    ]
  },
  {
    id: "sutliff-mixture-79",
    name: "Mixture No. 79",
    brand: "Sutliff",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Burley", "Virginia", "Black Cavendish"],
    origin: "United States",
    strength: 1,
    roomNote: 5,
    tinWeight: 57,
    price: 9.95,
    rating: 87,
    flavors: ["Cherry", "Sweet", "Vanilla", "Cream", "Mild Spice"],
    description: "Sutliff Mixture 79 is the classic American cherry aromatic — the tobacco that introduced a generation to pipe smoking. Light, sweet, and exceptionally easy to smoke, it combines a Burley-Virginia base with Black Cavendish and a pleasant cherry-vanilla topping. Simple, satisfying, and an excellent entry point for new pipe smokers or anyone wanting a no-fuss everyday blend.",
    pairings: ["Coffee", "Cola", "Lemonade"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/sutliff-mixture-no-79/AE0-TP.html", price: null },
    ]
  },
  {
    id: "stokkebye-luxury-twist-flake",
    name: "Luxury Twist Flake",
    brand: "Peter Stokkebye",
    blendType: "Virginia/Perique",
    cut: "Rope/Twist",
    components: ["Virginia", "Perique"],
    origin: "Denmark",
    strength: 3,
    roomNote: 4,
    tinWeight: 50,
    price: 14.95,
    rating: 92,
    flavors: ["Fruity", "Spicy", "Hay", "Dark Fruit", "Natural Sweet"],
    description: "One of the most distinctive Virginia/Perique blends available, Luxury Twist Flake is wound into a tight rope before being sliced into coins. The traditional rope construction allows the tobaccos to marry and deepen over time. Slice off what you need, rub it out, and enjoy a complex, fruity, peppery smoke that is simultaneously ancient and thoroughly compelling.",
    pairings: ["Scotch", "Dark Beer", "Tea"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/peter-stokkebye-luxury-twist-flake/PSD-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/peter-stokkebye-luxury-twist-flake", price: null },
    ]
  },
  {
    id: "wo-larsen-signature",
    name: "Signature",
    brand: "W.O. Larsen",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Virginia", "Burley", "Black Cavendish"],
    origin: "Denmark",
    strength: 1,
    roomNote: 5,
    tinWeight: 100,
    price: 29.99,
    rating: 88,
    flavors: ["Cherry", "Honey", "Vanilla", "Sweet", "Floral"],
    description: "W.O. Larsen is one of Copenhagen's most storied tobacconists, founded in 1864, and their Signature blend embodies the classic Danish aromatic tradition. Sweet and mild with a light cherry-honey topping over a smooth Virginia-Burley-Cavendish base. Elegant presentation and a delightfully pleasant room note have made it a perennial gift choice among those who appreciate old-world Danish craftsmanship.",
    pairings: ["Coffee", "Wine", "Tea"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/p/w-o-larsen-signature-pipe-tobacco/1440094/", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/w-o-larsen-signature-100g", price: 29.99 },
    ]
  },
  {
    id: "dunhill-nightcap",
    name: "Nightcap",
    brand: "Dunhill",
    blendType: "English",
    cut: "Ribbon",
    components: ["Virginia", "Latakia", "Oriental", "Perique"],
    origin: "United Kingdom",
    strength: 4,
    roomNote: 2,
    tinWeight: 50,
    price: 19.70,
    rating: 94,
    flavors: ["Latakia", "Earth", "Pepper", "Leather", "Wood Smoke"],
    description: "The legendary final-pipe-of-the-day blend, created by Alfred Dunhill for those last contemplative moments before sleep. Nightcap is a powerhouse English mixture — heavy Latakia smoke layered over full Virginias and Orientals, with a measure of Perique driving a peppery, warming finish. Rich, dark, and unapologetically bold. Inducted into virtually every 'greatest blends of all time' list ever written.",
    pairings: ["Islay Scotch", "Cognac", "Espresso"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/peterson-nightcap-pipe-tobacco/DHF-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/peterson-dunhill-nightcap-50g", price: 19.70 },
    ]
  },
  {
    id: "dunhill-my-mixture-965",
    name: "My Mixture 965",
    brand: "Dunhill",
    blendType: "English",
    cut: "Ribbon",
    components: ["Virginia", "Latakia", "Oriental", "Brown Cavendish"],
    origin: "United Kingdom",
    strength: 3,
    roomNote: 3,
    tinWeight: 50,
    price: 16.49,
    rating: 93,
    flavors: ["Latakia", "Cedar", "Earth", "Sweet", "Nuts"],
    description: "A Pipe Tobacco Hall of Fame inductee and perhaps the most beloved English blend ever made. My Mixture 965 marries fine Virginias with Macedonian Orientals and a generous portion of Cyprian Latakia, with brown Cavendish lending a subtle mellow sweetness that sets it apart from every other English on the shelf. Smooth, rich, endlessly smokeable — the blend many pipe smokers call home.",
    pairings: ["Scotch Whisky", "Black Coffee", "Stout"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/peterson-my-mixture-965-pipe-tobacco/DHE-TP.html", price: 16.49 },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/peterson-dunhill-my-mixture-965-50g", price: 16.75 },
    ]
  },
  {
    id: "samuel-gawith-squadron-leader",
    name: "Squadron Leader",
    brand: "Samuel Gawith",
    blendType: "English",
    cut: "Ribbon",
    components: ["Virginia", "Latakia", "Turkish"],
    origin: "United Kingdom",
    strength: 3,
    roomNote: 3,
    tinWeight: 50,
    price: 14.85,
    rating: 92,
    flavors: ["Latakia", "Earth", "Cedar", "Cream", "Mild Sweet"],
    description: "Perhaps the quintessential English blend, made in Kendal since the era it commemorates. Squadron Leader combines golden and stoved Virginias with earthy Turkish leaf and a measured dose of Latakia for a rich, cool, and amazingly smooth smoke. Never harsh, never overbearing — the English mixture to hand someone who wants to understand what the genre is all about.",
    pairings: ["English Breakfast Tea", "Scotch", "Coffee"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/samuel-gawith-squadron-leader/SGS-TP.html", price: 14.85 },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/samuel-gawith-squadron-leader-50g", price: null },
    ]
  },
  {
    id: "samuel-gawith-1792-flake",
    name: "1792 Flake",
    brand: "Samuel Gawith",
    blendType: "Dark Fired",
    cut: "Flake",
    components: ["Dark Fired Kentucky", "Tonquin Bean"],
    origin: "United Kingdom",
    strength: 5,
    roomNote: 2,
    tinWeight: 50,
    price: 16.95,
    rating: 90,
    flavors: ["Vanilla", "Dark Earth", "Wood Smoke", "Anise", "Molasses"],
    description: "Named for the year Samuel Gawith's Kendal factory began operation, 1792 Flake is one of the most distinctive tobaccos in the world. Dark-fired Kentucky leaf is steamed, pressed for days, and finished with tonquin bean — lending an exotic vanilla-anise perfume to an otherwise massive, earthy smoke. Strong enough to be approached with respect and a full stomach. A living piece of tobacco history.",
    pairings: ["Rum", "Port", "Strong Black Tea"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/samuel-gawith-1792-flake/SGA-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/samuel-gawith-1792-flake-50g", price: null },
    ]
  },
  {
    id: "escudo-navy-deluxe",
    name: "Navy De Luxe",
    brand: "Escudo",
    blendType: "Virginia/Perique",
    cut: "Coin",
    components: ["Virginia", "Perique"],
    origin: "Denmark",
    strength: 3,
    roomNote: 4,
    tinWeight: 50,
    price: 20.79,
    rating: 95,
    flavors: ["Fruity", "Spicy", "Natural Sweet", "Plum", "Bread"],
    description: "The gold standard of Virginia/Perique blends for more than 140 years. Choice US-grown Virginias and slowly fermented Louisiana Perique are pressed, spun into rope, and sliced into the iconic coins. Lightly sweet with real depth and a pleasant peppery spice — Escudo is the blend every other VaPer is measured against, and few have ever matched it.",
    pairings: ["Bourbon", "Red Wine", "Black Tea"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/escudo-navy-deluxe-pipe-tobacco/ESA-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/a-c-petersen-escudo-50g", price: 20.79 },
    ]
  },
  {
    id: "orlik-golden-sliced",
    name: "Golden Sliced",
    brand: "Orlik",
    blendType: "Virginia",
    cut: "Flake",
    components: ["Virginia", "Perique"],
    origin: "Denmark",
    strength: 2,
    roomNote: 4,
    tinWeight: 50,
    price: 13.89,
    rating: 92,
    flavors: ["Citrus", "Hay", "Honey", "Natural Sweet", "Grass"],
    description: "One of the most iconic Virginia flakes in the world, made in Assens, Denmark. Sweet, bright flue-cured Virginias are pressed and sliced with just an angel's breath of Perique for dimension. Easy to prepare — fold and stuff or fully rub — and effortlessly smokeable, with bright citrus and honey notes that have made it a favorite of Danish pipe makers for generations.",
    pairings: ["White Wine", "Tea", "Light Beer"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/orlik-golden-sliced/ORA-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/orlik-golden-sliced-50g", price: 13.89 },
    ]
  },
  {
    id: "gl-pease-westminster",
    name: "Westminster",
    brand: "G.L. Pease",
    blendType: "English",
    cut: "Ribbon",
    components: ["Virginia", "Latakia", "Oriental"],
    origin: "United States",
    strength: 3,
    roomNote: 3,
    tinWeight: 57,
    price: 14.88,
    rating: 93,
    flavors: ["Latakia", "Cedar", "Leather", "Sweet", "Earth"],
    description: "Gregory Pease's loving homage to the great London mixtures of old. Westminster layers smoky Cyprian Latakia over ripe red Virginias and fine Orientals in classic proportions — refined, balanced, and deeply traditional. Often cited as the finest modern recreation of the golden-age English style, it smokes cool and sweet from the first light to the bottom of the bowl.",
    pairings: ["Scotch Whisky", "Earl Grey Tea", "Coffee"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/p/gl-pease-westminster-pipe-tobacco/1472808", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/g-l-pease-westminster-2oz", price: 14.88 },
    ]
  },
  {
    id: "cornell-diehl-pirate-kake",
    name: "Pirate Kake",
    brand: "Cornell & Diehl",
    blendType: "Balkan",
    cut: "Crumble Cake",
    components: ["Latakia", "Burley", "Turkish"],
    origin: "United States",
    strength: 4,
    roomNote: 1,
    tinWeight: 57,
    price: 13.77,
    rating: 90,
    flavors: ["Latakia", "Campfire", "Leather", "Earth", "Wood Smoke"],
    description: "Seventy-five percent Latakia. That number tells you most of what you need to know about Pirate Kake — Cornell & Diehl's infamous smoke-bomb, pressed into crumble cake with Burley and Turkish to keep the colossal campfire character drinkable. Surprisingly smooth and cool for its strength, but make no mistake: this is a blend for committed Latakia lovers, smoked far from anyone who isn't.",
    pairings: ["Islay Scotch", "Black Coffee", "Mezcal"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/cornell-and-diehl-pirate-kake/CD2-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/cornell-diehl-pirate-kake-2oz", price: 13.77 },
    ]
  },
  {
    id: "stokkebye-luxury-navy-flake",
    name: "Luxury Navy Flake",
    brand: "Peter Stokkebye",
    blendType: "Virginia",
    cut: "Flake",
    components: ["Virginia"],
    origin: "Denmark",
    strength: 2,
    roomNote: 4,
    tinWeight: 50,
    price: 12.95,
    rating: 92,
    flavors: ["Natural Sweet", "Hay", "Citrus", "Toast", "Mild Spice"],
    description: "Perhaps the best value in all of pipe tobacco. Luxury Navy Flake is pure, sweet Virginia pressed into neat flakes with a whisper of natural rum essence in the old navy tradition. Bright, clean, and naturally sweet, it burns slow and cool with zero bite. Countless pipe smokers buy this by the pound — and for good reason.",
    pairings: ["Rum", "Tea", "Cider"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/peter-stokkebye-luxury-navy-flake/PSC-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/peter-stokkebye-luxury-navy-flake", price: null },
    ]
  },
  {
    id: "rattray-old-gowrie",
    name: "Old Gowrie",
    brand: "Rattray's",
    blendType: "Virginia",
    cut: "Broken Flake",
    components: ["Virginia"],
    origin: "Scotland",
    strength: 2,
    roomNote: 4,
    tinWeight: 50,
    price: 14.85,
    rating: 92,
    flavors: ["Hay", "Honey", "Citrus", "Bread", "Natural Sweet"],
    description: "A Rattray's classic from the great Scottish blending tradition. Old Gowrie is matured red Virginia in rubbed-out broken flake form — deep, bready sweetness with notes of honey and dried hay that build complexity as the bowl progresses. Charles Rattray blended for discerning Perth gentlemen over a century ago; this is one of the recipes that made his reputation.",
    pairings: ["Single Malt Scotch", "Shortbread", "Tea"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/rattray-s-old-gowrie/RAN-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/rattrays-old-gowrie-50g", price: 14.85 },
    ]
  },
  {
    id: "erinmore-flake",
    name: "Erinmore Flake",
    brand: "Erinmore",
    blendType: "Aromatic",
    cut: "Flake",
    components: ["Virginia", "Burley", "Dark Air-Cured"],
    origin: "United Kingdom",
    strength: 2,
    roomNote: 4,
    tinWeight: 50,
    price: 16.15,
    rating: 90,
    flavors: ["Fruity", "Floral", "Sweet", "Citrus", "Honey"],
    description: "A time-honored blend instantly recognizable by the pineapple on its tin — the old-world symbol of hospitality. Mature Virginias, mellow Burley, and sweet dark air-cured leaf are topped with a famously secret fruit essence, then pressed for three days to embed the flavor deep in the tobacco. Flowery, fruity, and utterly distinctive — there is nothing else quite like Erinmore.",
    pairings: ["Irish Whiskey", "Fruit Cake", "Tea"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/erinmore-flake-pipe-tobacco/EMA-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/erinmore-erinmore-flake-50g", price: 16.15 },
    ]
  },
  {
    id: "lane-bca",
    name: "BCA",
    brand: "Lane Limited",
    blendType: "Aromatic",
    cut: "Cavendish",
    components: ["Black Cavendish"],
    origin: "United States",
    strength: 1,
    roomNote: 5,
    tinWeight: 50,
    price: 10.95,
    rating: 88,
    flavors: ["Vanilla", "Sweet", "Caramel", "Cream", "Honey"],
    description: "The most popular black Cavendish on the market, full stop. Lane's BCA is fire-cured and steamed to silky black perfection, with a rich vanilla aroma that fills a room with goodwill. So gentle on the tongue it can be smoked all day, and so dependable that blenders everywhere use it as the foundation for their own aromatic creations.",
    pairings: ["Coffee", "Hot Chocolate", "Vanilla Ice Cream"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/lane-bca-pipe-tobacco/LBB-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/lane-limited-bulk-bca", price: null },
    ]
  },
  {
    id: "captain-black-original",
    name: "Original (White)",
    brand: "Captain Black",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Virginia", "Burley", "Black Cavendish"],
    origin: "United States",
    strength: 1,
    roomNote: 5,
    tinWeight: 42,
    price: 9.49,
    rating: 86,
    flavors: ["Vanilla", "Sweet", "Cream", "Caramel", "Mild Spice"],
    description: "The world's best-selling pipe tobacco for over 50 years. Captain Black Original — the famous 'White' pouch — blends Virginia, Burley, and Black Cavendish into a distinctively warm, sweet smoke whose room note is arguably the most recognized pipe aroma in America. Millions of smokers started here, and plenty never saw a reason to leave.",
    pairings: ["Coffee", "Cola", "Donuts"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/captain-black-original-pipe-tobacco/CBD-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/captain-black-white-1-5oz-pouch", price: 9.49 },
    ]
  },
  {
    id: "prince-albert-original",
    name: "Prince Albert",
    brand: "Prince Albert",
    blendType: "Burley",
    cut: "Crimp Cut",
    components: ["Burley"],
    origin: "United States",
    strength: 2,
    roomNote: 4,
    tinWeight: 42,
    price: 7.95,
    rating: 88,
    flavors: ["Cocoa", "Molasses", "Nuts", "Toast", "Mild Sweet"],
    description: "An American institution since 1907. Prince Albert's mahogany Burley delivers subtle cocoa and molasses in a crimp cut that packs easily and burns perfectly every time. This is the tobacco of porches, fishing trips, and grandfathers — a mellow, comforting, all-day smoke that has remained essentially unchanged for over a century because it never needed to change.",
    pairings: ["Coffee", "Lemonade", "Iced Tea"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/prince-albert-original/PAA-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/prince-albert-14oz-can", price: null },
    ]
  },
  {
    id: "carter-hall",
    name: "Carter Hall",
    brand: "Carter Hall",
    blendType: "Burley",
    cut: "Cross Cut",
    components: ["Burley", "Virginia"],
    origin: "United States",
    strength: 2,
    roomNote: 4,
    tinWeight: 42,
    price: 6.69,
    rating: 88,
    flavors: ["Nuts", "Cocoa", "Toast", "Mild Sweet", "Bread"],
    description: "The benchmark for over-the-counter tobacco and the answer to the question 'what should my first pipe tobacco be?' for generations. Mellow cross-cut Burleys blended with flake-cut Virginias and a subtle top note — Carter Hall packs effortlessly, burns cool and dry, and never bites. Simple, honest, and dependable in a way few things still are.",
    pairings: ["Coffee", "Beer", "Apple Pie"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/carter-hall/CHA-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/carter-hall-2oz", price: 6.69 },
    ]
  }
];
