/* ================================================================
   VITOLA PEDIA — Pipe Tobacco Database
   ================================================================ */

const PIPE_TOBACCOS = [
  {
    id: "lane-1q",
    name: "1-Q",
    brand: "Lane Limited",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Virginia", "Burley", "Black Cavendish"],
    origin: "United States",
    strength: 1,
    roomNote: 5,
    tinWeight: 50,
    price: 11.95,
    rating: 89,
    flavors: ["Vanilla", "Honey", "Caramel", "Sweet", "Cream"],
    description: "America's best-selling pipe tobacco for decades. Lane 1-Q is the definitive mild aromatic — a pillowy blend of Virginias, Burley, and Black Cavendish lightly cased with vanilla and honey. Burns cool and dry with a sweet room note that made it legendary among beginners and seasoned smokers alike. If you've ever smelled a pleasant pipe wafting down the street, there's a good chance it was 1-Q.",
    pairings: ["Coffee", "Apple Cider", "Hot Chocolate"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/p/lane-1-q-pipe-tobacco/1439894/", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/lane-limited-bulk-1-q", price: null },
    ]
  },
  {
    id: "dunhill-early-morning-pipe",
    name: "Early Morning Pipe",
    brand: "Dunhill",
    blendType: "English",
    cut: "Ribbon",
    components: ["Virginia", "Latakia", "Oriental"],
    origin: "United Kingdom",
    strength: 1,
    roomNote: 3,
    tinWeight: 50,
    price: 17.95,
    rating: 90,
    flavors: ["Cedar", "Hay", "Floral", "Mild Latakia", "Sweet"],
    description: "One of Alfred Dunhill's most beloved creations, designed for the first pipe of the day. A light English mixture with a gentle touch of Latakia over a base of bright Virginias and sweet Orientals. Cool, gentle, and refined — it builds complexity as it burns down. Now blended by Peterson under license, the formula remains faithful to the original Dunhill recipe.",
    pairings: ["Black Tea", "Coffee", "Orange Juice"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/peterson-early-morning-pipe-tobacco/DHD-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/peterson-dunhill-early-morning-pipe-50g", price: 16.70 },
    ]
  },
  {
    id: "dunhill-london-mixture",
    name: "London Mixture",
    brand: "Dunhill",
    blendType: "English",
    cut: "Ribbon",
    components: ["Virginia", "Latakia", "Oriental", "Perique"],
    origin: "United Kingdom",
    strength: 2,
    roomNote: 3,
    tinWeight: 50,
    price: 17.95,
    rating: 92,
    flavors: ["Latakia", "Earth", "Cedar", "Spice", "Leather"],
    description: "The classic medium English mixture that defined the London style. London Mixture balances smoky Latakia with sweet Virginias and spicy Orientals, with a hint of Perique adding depth and complexity. A sophisticated smoke that rewards patience — from a gentle, grassy opening to a rich leather-and-earth finish. The true benchmark of the English genre.",
    pairings: ["Scotch Whisky", "Black Coffee", "Aged Bourbon"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/p/dunhill-london-mixture-pipe-tobacco/1439874/", price: null },
    ]
  },
  {
    id: "samuel-gawith-full-virginia-flake",
    name: "Full Virginia Flake",
    brand: "Samuel Gawith",
    blendType: "Virginia",
    cut: "Flake",
    components: ["Virginia"],
    origin: "United Kingdom",
    strength: 2,
    roomNote: 4,
    tinWeight: 250,
    price: 22.95,
    rating: 93,
    flavors: ["Hay", "Bread", "Citrus", "Natural Sweet", "Grass"],
    description: "A pressed flake made entirely from fine Virginia tobaccos, produced at the historic Gawith & Hoggarth factory in Kendal, England. Full Virginia Flake must be rubbed out or folded before packing — a ritual that rewards the patient smoker with natural sweetness, bright hay, a hint of citrus, and a clean, dry finish that develops beautifully from top to bottom. Pure Virginia at its most expressive.",
    pairings: ["Tea", "Lemonade", "Light White Wine"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/samuel-gawith-full-virginia-flake/SGK-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/samuel-gawith-full-virginia-flake-250g", price: null },
    ]
  },
  {
    id: "peterson-irish-flake",
    name: "Irish Flake",
    brand: "Peterson",
    blendType: "Virginia/Perique",
    cut: "Flake",
    components: ["Virginia", "Perique"],
    origin: "Ireland",
    strength: 2,
    roomNote: 4,
    tinWeight: 50,
    price: 13.99,
    rating: 92,
    flavors: ["Fruity", "Spicy", "Sweet", "Plum", "Hay"],
    description: "Peterson's Irish Flake is one of the most celebrated Virginia/Perique blends on the market. Pressed flakes of fine bright Virginias interleaved with peppery Perique from St. James Parish, Louisiana — rubbing them out releases a heady, fruity aroma. Spicy and sweet with a long, natural finish that lingers pleasantly. A cornerstone of any serious pipe tobacco collection.",
    pairings: ["Irish Whiskey", "Tea", "Apple Juice"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/peterson-irish-flake/PTE-TP.html", price: 13.99 },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/peterson-irish-flake-50g", price: 14.50 },
    ]
  },
  {
    id: "mac-baren-hh-old-dark-fired",
    name: "HH Old Dark Fired",
    brand: "Mac Baren",
    blendType: "Dark Fired",
    cut: "Ready Rubbed",
    components: ["Kentucky Fire Cured", "Virginia", "Burley"],
    origin: "Denmark",
    strength: 4,
    roomNote: 2,
    tinWeight: 50,
    price: 15.95,
    rating: 91,
    flavors: ["Campfire", "Dark Earth", "Dried Fruit", "Wood Smoke", "Molasses"],
    description: "Mac Baren's tribute to the classic dark-fired Kentucky tradition. HH Old Dark Fired centers on air-cured and fire-cured Kentucky leaf, imparting a rich, woody campfire character that mingles with sweet Virginias and robust Burley. An acquired taste for experienced smokers — intense, complex, and deeply satisfying on a cold night. Not for the faint of heart.",
    pairings: ["Bourbon", "Dark Beer", "Campfire Coffee"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/mac-baren-hh-old-dark-fired/MRG-TB.html", price: null },
    ]
  },
  {
    id: "gl-pease-quiet-nights",
    name: "Quiet Nights",
    brand: "G.L. Pease",
    blendType: "Balkan",
    cut: "Ribbon",
    components: ["Virginia", "Latakia", "Oriental", "Perique"],
    origin: "United States",
    strength: 3,
    roomNote: 2,
    tinWeight: 57,
    price: 17.50,
    rating: 94,
    flavors: ["Latakia", "Earth", "Spice", "Dark Fruit", "Cedar", "Leather"],
    description: "One of G.L. Pease's finest creations, Quiet Nights is a full-flavored Balkan blend that invites contemplation. Smoky Latakia is tempered by complex Orientals and bright Red Virginias, with just enough Perique to add a peppery, fruity dimension. This is a fireplace blend — rich, layered, and deeply satisfying on a cool evening with something substantial in the glass.",
    pairings: ["Scotch Whisky", "Brandy", "Dark Roast Coffee"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/gl-pease-quiet-nights/GLY-TP.html", price: 17.50 },
    ]
  },
  {
    id: "rattray-hal-o-the-wynd",
    name: "Hal O' The Wynd",
    brand: "Rattray's",
    blendType: "Virginia/Perique",
    cut: "Broken Flake",
    components: ["Virginia", "Perique"],
    origin: "Scotland",
    strength: 3,
    roomNote: 4,
    tinWeight: 100,
    price: 21.95,
    rating: 93,
    flavors: ["Fruity", "Spicy", "Dark Fruit", "Hay", "Sweet Pepper"],
    description: "Named after a character from Sir Walter Scott's 'The Fair Maid of Perth,' Hal O' The Wynd is Rattray's masterwork in the Virginia/Perique tradition. Bold, peppery Perique pushes against naturally sweet Red and Light Virginias in broken flake form — earthy, fruity, and complex with a long, warming finish. A quintessential Scottish blend for afternoon reflection.",
    pairings: ["Single Malt Scotch", "Dark Tea", "Port Wine"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/rattray-s-hal-o--the-wynd/RAJ-TP.html", price: 14.94 },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/rattrays-hal-o-the-wynd-100g", price: null },
    ]
  },
  {
    id: "solani-aged-burley-flake-636",
    name: "Aged Burley Flake No. 636",
    brand: "Solani",
    blendType: "Virginia/Burley",
    cut: "Flake",
    components: ["Virginia", "Burley"],
    origin: "Germany",
    strength: 2,
    roomNote: 4,
    tinWeight: 50,
    price: 13.95,
    rating: 93,
    flavors: ["Nuts", "Cream", "Natural Sweet", "Hay", "Bread"],
    description: "A German masterwork of restraint and balance. Solani 636 presses aged Virginia and Burley leaf into a dense, aromatic flake that burns slowly and evenly. No topping, no casing — just pure leaf, aged to bring out natural sweetness and nuttiness. The result is a naturally sweet, creamy, and satisfying smoke that rewards those willing to slow down and pay attention.",
    pairings: ["Coffee", "Beer", "Iced Tea"],
    image: null,
    buyLinks: []
  },
  {
    id: "cornell-diehl-autumn-evening",
    name: "Autumn Evening",
    brand: "Cornell & Diehl",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Virginia", "Burley", "Black Cavendish"],
    origin: "United States",
    strength: 2,
    roomNote: 5,
    tinWeight: 57,
    price: 13.95,
    rating: 91,
    flavors: ["Maple", "Caramel", "Vanilla", "Toasted Nuts", "Sweet"],
    description: "Cornell & Diehl's most beloved aromatic. Autumn Evening takes a robust Burley-Virginia base and tops it lightly with maple and vanilla — resulting in a naturally sweet smoke that tastes as good as it smells. The Black Cavendish adds moisture and a silky, smooth texture. As close to a perfect Sunday afternoon smoke as any tobacco in production.",
    pairings: ["Bourbon", "Apple Cider", "Hot Coffee"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/cornell-and-diehl-autumn-evening/001-CDA.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/copy-of-cornell-diehl-autumn-evening-8oz", price: null },
    ]
  },
  {
    id: "mac-baren-original-choice",
    name: "Original Choice",
    brand: "Mac Baren",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Virginia", "Burley", "Black Cavendish"],
    origin: "Denmark",
    strength: 1,
    roomNote: 5,
    tinWeight: 100,
    price: 17.95,
    rating: 89,
    flavors: ["Sweet", "Vanilla", "Caramel", "Mild Spice", "Honey"],
    description: "Mac Baren's Original Choice is the quintessential Danish aromatic — mild, smooth, and sweetly satisfying. Virginia, Burley, and Black Cavendish are blended in the classic Danish tradition and lightly topped with sweet floral and vanilla notes. A pleasant room note and effortless burn make it an excellent everyday aromatic that punches well above its price point.",
    pairings: ["Coffee", "Milk Tea", "Hot Chocolate"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/mac-baren-classics-original-choice/MBT-TP.html", price: null },
    ]
  },
  {
    id: "capstan-original-flake-blue",
    name: "Original Flake Blue",
    brand: "Capstan",
    blendType: "Virginia",
    cut: "Flake",
    components: ["Virginia"],
    origin: "United Kingdom",
    strength: 2,
    roomNote: 4,
    tinWeight: 50,
    price: 15.95,
    rating: 91,
    flavors: ["Hay", "Natural Sweet", "Citrus", "Toast", "Grass"],
    description: "Capstan is one of Britain's oldest and most enduring pipe tobacco brands, with origins in the Victorian era. The Blue (Medium) flake is pure pressed Virginia leaf — unadulterated tobacconicness at its finest, relying entirely on natural sweetness for its character. Pack it, slow down, and enjoy natural Virginia sweetness, bright grass, and a clean, toasty finish.",
    pairings: ["Black Tea", "Ginger Beer", "White Wine"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/capstan-original-flake/CPB-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/capstan-flake-blue-50g", price: 24.99 },
    ]
  },
  {
    id: "sutliff-mixture-79",
    name: "Mixture No. 79",
    brand: "Sutliff",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Burley", "Virginia", "Black Cavendish"],
    origin: "United States",
    strength: 1,
    roomNote: 5,
    tinWeight: 57,
    price: 9.95,
    rating: 87,
    flavors: ["Cherry", "Sweet", "Vanilla", "Cream", "Mild Spice"],
    description: "Sutliff Mixture 79 is the classic American cherry aromatic — the tobacco that introduced a generation to pipe smoking. Light, sweet, and exceptionally easy to smoke, it combines a Burley-Virginia base with Black Cavendish and a pleasant cherry-vanilla topping. Simple, satisfying, and an excellent entry point for new pipe smokers or anyone wanting a no-fuss everyday blend.",
    pairings: ["Coffee", "Cola", "Lemonade"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/sutliff-mixture-no-79/AE0-TP.html", price: null },
    ]
  },
  {
    id: "stokkebye-luxury-twist-flake",
    name: "Luxury Twist Flake",
    brand: "Peter Stokkebye",
    blendType: "Virginia/Perique",
    cut: "Rope/Twist",
    components: ["Virginia", "Perique"],
    origin: "Denmark",
    strength: 3,
    roomNote: 4,
    tinWeight: 50,
    price: 14.95,
    rating: 92,
    flavors: ["Fruity", "Spicy", "Hay", "Dark Fruit", "Natural Sweet"],
    description: "One of the most distinctive Virginia/Perique blends available, Luxury Twist Flake is wound into a tight rope before being sliced into coins. The traditional rope construction allows the tobaccos to marry and deepen over time. Slice off what you need, rub it out, and enjoy a complex, fruity, peppery smoke that is simultaneously ancient and thoroughly compelling.",
    pairings: ["Scotch", "Dark Beer", "Tea"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/product/peter-stokkebye-luxury-twist-flake/PSD-TP.html", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/peter-stokkebye-luxury-twist-flake", price: null },
    ]
  },
  {
    id: "wo-larsen-signature",
    name: "Signature",
    brand: "W.O. Larsen",
    blendType: "Aromatic",
    cut: "Ribbon",
    components: ["Virginia", "Burley", "Black Cavendish"],
    origin: "Denmark",
    strength: 1,
    roomNote: 5,
    tinWeight: 100,
    price: 29.99,
    rating: 88,
    flavors: ["Cherry", "Honey", "Vanilla", "Sweet", "Floral"],
    description: "W.O. Larsen is one of Copenhagen's most storied tobacconists, founded in 1864, and their Signature blend embodies the classic Danish aromatic tradition. Sweet and mild with a light cherry-honey topping over a smooth Virginia-Burley-Cavendish base. Elegant presentation and a delightfully pleasant room note have made it a perennial gift choice among those who appreciate old-world Danish craftsmanship.",
    pairings: ["Coffee", "Wine", "Tea"],
    image: null,
    buyLinks: [
      { retailer: "Pipes & Cigars", url: "https://www.pipesandcigars.com/p/w-o-larsen-signature-pipe-tobacco/1440094/", price: null },
      { retailer: "4 Noggins", url: "https://www.4noggins.com/products/w-o-larsen-signature-100g", price: 29.99 },
    ]
  }
];
